export const SET_FEATURED = 'SET FEATURED CHARACTER';
export const TOGGLE_FAVOURITE = 'TOGGLE FAVOURITE CHARACTER';

export const GET_CHARACTERS_SUCCESS = 'GET CHARACTERS SUCCESS';
export const GET_CHARACTERS_FAILURE = 'GET CHARACTERS_FAILURE';
